### ISSUE TITLE
Add support to attributes without default values

### ISSUE THREAD

**Issue by miikargh** [yukihiko-shinoda/yaml-dataclass-config#13]
# Problem
`yaml-data-class-config` doesn't currently support attributes without default values.

# Cause
The attribute `FILE_PATH` in [config.py](https://github.com/yukihiko-shinoda/yaml-dataclass-config/blob/bf4bd87b4afef98ed8de24b853fd1f6aa7592c4c/yamldataclassconfig/config.py#L20) that does not have a default value causes the error.

# Possible solution
Remove the `FILE_PATH` attribute or add it after the `config.yml` is loaded so that it doesn't cause problems with mypy.

# Example
`config.yml`:
```yaml
property_a: 1
property_b: '2'
```

`example.py`:
```python
from dataclasses import dataclass, field
from yamldataclassconfig.config import YamlDataClassConfig


@dataclass
class Config(YamlDataClassConfig):
    property_a: int
    property_b: str
```
Running `mypy example.py` throws the following errors:
```sh
problem.py:7: error: Attributes without a default cannot follow attributes with one
problem.py:8: error: Attributes without a default cannot follow attributes with one
Found 2 errors in 1 file (checked 1 source file)
```

One can go around this problem by adding `Union[None, <type>]` to every attribute but this is not ideal since one might want to have attributes that throw error if no value is provided.

## Environment
- Ubuntu 20.04.1 LTS x86_64
- mypy==0.782
- python==3.8.5

Thanks for the great library by the way!

**Comment by yukihiko-shinoda** [comment]
Hi, thanks for your feedback!

I deployed new version 1.4.0, would you check it ?
`FILE_PATH` was already specified as `field(init=False)`,
however, mypy seems to not check it if its definition is return value of method.
I checked it recovered by this update.
https://github.com/yukihiko-shinoda/yaml-dataclass-config/commit/163532d0bfaf84c4028129b653fbffa2e445f987

config.yml:

```yaml
property_a: 1
property_b: '2'
```

test.py:

```python
from dataclasses import dataclass
from yamldataclassconfig.config import YamlDataClassConfig

@dataclass
class Config(YamlDataClassConfig):
    property_a: int
    property_b: str


CONFIG: Config = Config(0, "1")
CONFIG.load()
print(CONFIG.property_a)
print(CONFIG.property_b)
```

Result:

```console
$ pipenv run python test.py
1
2
$ pipenv run mypy test.py
Success: no issues found in 1 source file
```

**Comment by miikargh** [comment]
Seems to work well after updating to `yamldataclassconfig==1.4.0`. Thanks a bunch!
